<a href="https://colab.research.google.com/github/Lucas-procopio/Data-Analysis/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing lib
import numpy as np

In [2]:
# Version
print(np.__version__)

1.21.6


In [4]:
# Creating a grid
array = np.array([10,20,30,40,50])

array

array([10, 20, 30, 40, 50])

In [8]:
type(array)

numpy.ndarray

In [10]:
duas = np.array([[10, 9, 8, 7, 6],
                [5, 4, 3, 2, 1]]
                )

print(duas)

[[10  9  8  7  6]
 [ 5  4  3  2  1]]


In [11]:
tres = np.array([
                 [15, 14, 13, 12, 11],
                 [10, 9, 8, 7, 6],
                 [5, 4, 3, 2, 1]
])

print(tres)

[[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


In [12]:
# Testing

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
estressando_NP = np.arange(1000000)
estressando_NP_02 = np.arange(5000000)
print(len(estressando_NP),len(estressando_NP_02))

1000000 5000000


In [16]:
# 1° Test (calculando o tempo de processamento da variável sem o numpy)
%time for loop in estressando_NP: pass

CPU times: user 81.8 ms, sys: 407 µs, total: 82.2 ms
Wall time: 85.9 ms


In [19]:
#2° test
%time for loop in estressando_NP_02: pass

CPU times: user 398 ms, sys: 0 ns, total: 398 ms
Wall time: 402 ms
